version: "3.2"
services:
#based on https://x-team.com/blog/docker-compose-php-environment-from-scratch/, http://geekyplatypus.com/dockerise-your-php-application-with-nginx-and-php7-fpm/
  php-fpm:
    image: betoscopio/php74alpine-d7:1.0-sqlc
    #build:
    #  context: ./images/php74alpine-D7
    #  dockerfile: Dockerfile
    #Requires access to the code too
    restart: unless-stopped
    volumes:
    #  - ./src/web:/var/www/
      - ./src/drupal-7.81:/var/www/
  database:
    # more info:
    # https://dev.mysql.com/doc/mysql-installation-excerpt/5.7/en/docker-mysql-more-topics.html
    # https://hub.docker.com/_/mariadb
    image: mariadb:10.5-focal
#    image: mysql:8.0.13
#    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    # Move to external file
    #env_file:
    #  - pi.env
    environment:
      - MYSQL_DATABASE=mydb
    #  - MYSQL_USER=${DB_USER}
      - MYSQL_USER=myuser
    #  - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=mypass
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./data:/var/lib/mysql
  nginx:
    image: nginx:stable
    labels:
      description: Nginx Backend Webserver
      name: nginx backend
    container_name: nginx-server-drupal
    restart: unless-stopped
    volumes:
      - ./src/drupal:/var/www/
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/sites/:/etc/nginx/sites-available
      - ./conf/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "8081:80"

